name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: ./.github/actions/my-action

      - name: Run API Tests
        run: newman run "operation of employees.postman_collection.json" -e Testnewman.postman_environment.json
